version: "3.8"

services:
  web-server:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - "./conf/online-shop.conf:/etc/nginx/nginx.conf"
      - "./static:/static"
    ports:
      - "80:80"

  app:
    image: app
    volumes:
      - "./:/app"

  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
