version: "3.8"

services:
  web-server:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - "./conf/online-shop.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"

  app:
    image: app
    volumes:
      - "./:/app"

  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root

  # dragonflydb:
    # cache